name:                metar
version:             0.1.0.0
github:              "naushadh/metar"
license:             BSD3
author:              "Naushadh"
maintainer:          "naushadh@protonmail.com"
copyright:           "2018 Naushadh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/naushadh/metar#readme>

dependencies:
- base >= 4.7 && < 5
- text
- time
- parser-combinators
- megaparsec
- conduit
- containers
- bytestring
- QuickCheck
- quickcheck-instances

library:
  source-dirs: src

executables:
  metar:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metar
    - optparse-applicative

tests:
  metar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metar
    - tasty
    - tasty-quickcheck
